# dcload-serial Makefile Configuration

# Detect the host
ROOTDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(ROOTDIR)/Makefile.hostdetect

# Host compiler and flags
HOSTCC			= gcc
HOSTCFLAGS		= -O2 -I/usr/local/include
HOSTLDFLAGS		= -L/usr/local/lib

# For MinGW/MSYS, MinGW-w64/MSYS2 and Cygwin
ifdef WINDOWS
  HOSTCFLAGS += -D_WIN32
  EXECUTABLEEXTENSION = .exe
endif

# dc compiler prefix -- this is usually what you used for --prefix when
# building your compiler.
TARGETPREFIX	= /opt/toolchains/dc/sh-elf

# dir to install dc-tool in
TOOLINSTALLDIR	= /opt/toolchains/dc/bin

# To build dc-tool, we need to use libelf or libfd
# By default, libelf is used

# Define this if you want to use libbfd instead of libelf (which is default)
WITH_BFD = 0

# For MinGW/MSYS, we need to use libbfd instead of libelf
ifdef MINGW
  WITH_BFD = 1
endif

# You may have to change the paths for BFDLIB and BFDINCLUDE to the correct 
# ones for your system. These must point to your sh-elf bfd, not the system one!
# If you built the dc-chain with the v0.4, you'll have it installed in the
# correct location.
BFDLIB			= $(TARGETPREFIX)/lib
BFDINCLUDE		= $(TARGETPREFIX)/include

# When using libelf instead of BFD, these must point to your
# libelf installation (leave empty or undefined if libelf is part of the system)
ELFLIB			= $(TARGETPREFIX)/lib
ELFINCLUDE		= $(TARGETPREFIX)/include

# For macOS, libelf is here when installed through Homebrew
ifdef MACOS
  ELFINCLUDE	= /usr/local/include/libelf
endif

# sh-elf-stuff
# You don't need to change these
TARGETCC		= $(TARGETPREFIX)/bin/sh-elf-gcc
TARGETCFLAGS	= -O2 -ml -m4-single-only
TARGETOBJCOPY	= $(TARGETPREFIX)/bin/sh-elf-objcopy -R .stack
TARGETLD		= $(TARGETPREFIX)/bin/sh-elf-ld

# set TARGETCCVER to 3 or 4, depending on your SH compiler version (gcc 3.x or gcc 4.x)
# this line tries to detect the version automatically
TARGETCCVER		= $(shell $(TARGETCC) --version | head -1 | sed  "s/.* \([[:digit:]][[:digit:]]*\)\.[[:digit:]][[:digit:]]*.*/\1/")

# You generally shouldn't change this unless you are making forked
# versions (or test versions)
VERSION			= 1.0.5

# MinGW/MSYS
# Define this if you want a standalone, no dependency binary
# When the binary is standalone, it can be run outside MSYS environment
#STANDALONE_BINARY = 1

# this is the default port for dc-tool, it can be changed on the commandline
SERIALDEVICE	= /dev/ttyS0

# macOS -- you'll need to go look in /dev to see what the actual device
# name is, and depending on the device, it must be plugged into the same
# port each time.
#SERIALDEVICE	= /dev/cu.usbserial-5B24

ifdef WINDOWS
  SERIALDEVICE = COM1
endif

# default serial speed - YOU DO NOT NEED TO CHANGE THIS
SERIALSPEED	= 57600
